### ISSUE TITLE
需修改AriaNg的aria-ng-46df9fae24.min.js

### ISSUE THREAD

**Issue by kuenming** [Auska/docker-aria2#1]
需修改AriaNg的aria-ng-46df9fae24.min.js 的原始碼,才能無限制設定 max-connection-per-server (原本上限成16)
原
'max-connection-per-server': {type: 'integer',defaultValue: '1',required: true,min: 1,max: 16}
改成
'max-connection-per-server': {type: 'integer',defaultValue: '1',required: true,min: 1}

**Comment by Auska** [comment]
感谢 新版本已修复
